/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Ulrich TIAYO NGNINGAHE <tiayo.pro@gmail.com>
 */
public class GameJFrame extends javax.swing.JFrame {

    private Integer grid[][];
    private final int WON = 1;
    private final int DRAW = 2;
    private final int NONE = 0;
    private int moves = 0;
    private int gridSize = 3;

    /**
     * Creates new form GameJFrame
     */
    public GameJFrame() {
        initComponents();
        grid = new Integer[gridSize][gridSize];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        b11JButton = new javax.swing.JButton();
        b12JButton = new javax.swing.JButton();
        b13JButton = new javax.swing.JButton();
        b21JButton = new javax.swing.JButton();
        b22JButton = new javax.swing.JButton();
        b23JButton = new javax.swing.JButton();
        b31JButton = new javax.swing.JButton();
        b32JButton = new javax.swing.JButton();
        b33JButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        newGameJMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        quitterJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 3, 3));

        b11JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b11JButton);

        b12JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b12JButton);

        b13JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b13JButton);

        b21JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b21JButton);

        b22JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b22JButton);

        b23JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b23JButton);

        b31JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b31JButton);

        b32JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b32JButton);

        b33JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33JButtonActionPerformed(evt);
            }
        });
        jPanel2.add(b33JButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newGameJMenu.setText("Jeu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nouvelle partie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        newGameJMenu.add(jMenuItem1);

        quitterJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitterJMenuItem.setText("Quitter");
        quitterJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterJMenuItemActionPerformed(evt);
            }
        });
        newGameJMenu.add(quitterJMenuItem);

        jMenuBar1.add(newGameJMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitterJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterJMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitterJMenuItemActionPerformed

    private void b11JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11JButtonActionPerformed
        handlePlay(b11JButton, 0, 0);
    }//GEN-LAST:event_b11JButtonActionPerformed

    private void b12JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12JButtonActionPerformed
        handlePlay(b12JButton, 0, 1);
    }//GEN-LAST:event_b12JButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (moves != 0) {
            int result = JOptionPane.showConfirmDialog(null, "La partie en cours sera perdue! Continuer?");
            if (result != JOptionPane.YES_OPTION) {
                return;
            }
        }

        grid = new Integer[gridSize][gridSize];
        moves = 0;
        b11JButton.setIcon(null);
        b11JButton.setEnabled(true);

        b12JButton.setIcon(null);
        b12JButton.setEnabled(true);

        b13JButton.setIcon(null);
        b13JButton.setEnabled(true);

        b21JButton.setIcon(null);
        b21JButton.setEnabled(true);

        b22JButton.setIcon(null);
        b22JButton.setEnabled(true);

        b23JButton.setIcon(null);
        b23JButton.setEnabled(true);

        b31JButton.setIcon(null);
        b31JButton.setEnabled(true);

        b32JButton.setIcon(null);
        b32JButton.setEnabled(true);

        b33JButton.setIcon(null);
        b33JButton.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void b13JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13JButtonActionPerformed
        handlePlay(b13JButton, 0, 2);
    }//GEN-LAST:event_b13JButtonActionPerformed

    private void b21JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21JButtonActionPerformed
        handlePlay(b21JButton, 1, 0);
    }//GEN-LAST:event_b21JButtonActionPerformed

    private void b22JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22JButtonActionPerformed
        handlePlay(b22JButton, 1, 1);
    }//GEN-LAST:event_b22JButtonActionPerformed

    private void b23JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23JButtonActionPerformed
        handlePlay(b23JButton, 1, 2);
    }//GEN-LAST:event_b23JButtonActionPerformed

    private void b31JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31JButtonActionPerformed
        handlePlay(b31JButton, 2, 0);
    }//GEN-LAST:event_b31JButtonActionPerformed

    private void b32JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32JButtonActionPerformed
        handlePlay(b32JButton, 2, 1);
    }//GEN-LAST:event_b32JButtonActionPerformed

    private void b33JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33JButtonActionPerformed
        handlePlay(b33JButton, 2, 2);
    }//GEN-LAST:event_b33JButtonActionPerformed

    private void handlePlay(JButton button, int rowInd, int colInd) {
        button.setEnabled(false);
        if (moves % 2 == 0) {
            button.setIcon(new ImageIcon(getClass().getResource("/resources/cercle.png")));
        } else {
            button.setIcon(new ImageIcon(getClass().getResource("/resources/croix.png")));
        }
        int result = play(rowInd, colInd);
        switch (result) {
            case WON:
                JOptionPane.showMessageDialog(null, "Le joueur " + grid[rowInd][colInd] + " a gagné la partie.");
                break;
            case DRAW:
                JOptionPane.showMessageDialog(null, "Egalité");
                break;
        }
    }

    private int play(int rowInd, int colInd) {
        if (moves % 2 == 0) {
            grid[rowInd][colInd] = 1;
        } else {
            grid[rowInd][colInd] = 2;
        }
        moves++;
        int row = 0, col = 0, diag1 = 0, diag2 = 0, nulls = 0;
        for (int i = 0; i < gridSize; i++) {
            for (int j = 0; j < gridSize; j++) {
                if (grid[i][j] == null) {
                    nulls++;
                }
            }
            if (Objects.equals(grid[rowInd][i], grid[rowInd][colInd])) {
                row++;
            }
            if (Objects.equals(grid[i][colInd], grid[rowInd][colInd])) {
                col++;
            }
            if (Objects.equals(grid[i][i], grid[rowInd][colInd])) {
                diag1++;
            }
            if (Objects.equals(grid[i][gridSize - i - 1], grid[rowInd][colInd])) {
                diag2++;
            }
        }
        if (row == gridSize || col == gridSize || diag1 == gridSize || diag2 == gridSize) {
            return WON;
        }

        if (nulls == 0) {
            return DRAW;
        }

        return NONE;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameJFrame frame = new GameJFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b11JButton;
    private javax.swing.JButton b12JButton;
    private javax.swing.JButton b13JButton;
    private javax.swing.JButton b21JButton;
    private javax.swing.JButton b22JButton;
    private javax.swing.JButton b23JButton;
    private javax.swing.JButton b31JButton;
    private javax.swing.JButton b32JButton;
    private javax.swing.JButton b33JButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu newGameJMenu;
    private javax.swing.JMenuItem quitterJMenuItem;
    // End of variables declaration//GEN-END:variables
}
